app <- ShinyDriver$new("../", seed = 1)
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(model_url_1 = "https://docs.google.com/spreadsheets/d/1XdpAKFyEpGjPmI3UZYYK4zQw-RUzKWD2_GJnp3LO_Pk/edit?usp=sharing", wait_=FALSE, values_=FALSE)
app$snapshot()
app$setInputs(reevaluate = "click", wait_=FALSE, values_=FALSE)
app$snapshot()
app$snapshot()
app$setInputs(model_url_2 = "https://docs.google.com/spreadsheets/d/1XdpAKFyEpGjPmI3UZYYK4zQw-RUzKWD2_GJnp3LO_Pk/edit?usp=sharing", wait_=FALSE, values_=FALSE)
app$snapshot()
app$snapshot()
app$snapshot()
app$setInputs(cut_h = 530)
app$setInputs(cut_h = 405)
app$snapshot()
app$setInputs(reaction_filter = "ACHBS")
app$setInputs(reaction_filter = c("ACHBS", "ACLS"))
app$setInputs(reaction_filter = c("ACHBS", "ACLS", "DHAD1"))
app$setInputs(reaction_filter = c("ACHBS", "ACLS", "DHAD1", "DHAD2"))
app$setInputs(reaction_filter = c("ACHBS", "ACLS", "DHAD1", "DHAD2", "ILETA"))
app$setInputs(reaction_filter = c("ACHBS", "ACLS", "DHAD1", "DHAD2", "ILETA", "IPMD"))
app$setInputs(reaction_filter = c("ACHBS", "ACLS", "DHAD1", "DHAD2", "ILETA", "IPMD", "IPPMIa"))
app$setInputs(reaction_filter = c("ACHBS", "ACLS", "DHAD1", "DHAD2", "ILETA", "IPMD", "IPPMIa", "IPPMIb"))
app$setInputs(reaction_filter = c("ACHBS", "ACLS", "DHAD1", "DHAD2", "ILETA", "IPMD", "IPPMIa", "IPPMIb", "IPPS"))
app$snapshot()
app$snapshot()
app$snapshot()
